import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const css = readFileSync(join(root, 'src/ui/theme.css'), 'utf8');
const script = readFileSync(join(root, 'src/ui/application.js'), 'utf8');
for (const page of ['login', 'dashboard', 'admin']) {
  const html = `<!doctype html>\n<!-- Generated by scripts/build-ui.mjs; edit src/ui/theme.css and application.js. -->\n<html lang="sr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page === 'login' ? 'Prijava' : page === 'admin' ? 'Administracija' : 'Pregled prodavnice'} | MerchantPro Lab</title><style>${css}</style></head><body data-page="${page}"><div id="app"></div><script>${script}</script></body></html>\n`;
  for (const folder of ['src/ui', 'ui', 'dist/ui']) {
    mkdirSync(join(root, folder), { recursive: true });
    writeFileSync(join(root, folder, page + '.html'), html);
  }
}
